apiVersion: v1
kind: Service
metadata:
  name: clientui-service
  labels:
    name: clientui-service
    app: picvista-app

spec:
  type: NodePort
  ports:
    - port: 5015
      targetPort: 5015
      nodePort: 30004
  selector:
    name: clientui-microservice
    app: picvista-app
