apiVersion: v1
kind: Pod
metadata:
  name: comment-pod
  labels:
    name: comment-microservice
    app: picvista-app

spec:
  containers:
    - name: picvista-comment
      image: rachidouhammou/picvista-comment
      ports:
        - containerPort: 5013
