apiVersion: v1
kind: Service
metadata:
  name: comment-service
  labels:
    name: comment-service
    app: picvista-app

spec:
  ports:
    - port: 5013
      targetPort: 5013
  selector:
    name: comment-microservice
    app: picvista-app