apiVersion: v1
kind: Service
metadata:
  name: image-service
  labels:
    name: image-service
    app: picvista-app

spec:
  ports:
    - port: 5012
      targetPort: 5012
  selector:
    name: image-microservice
    app: picvista-app