apiVersion: v1
kind: Pod
metadata:
  name: image-pod
  labels:
    name: image-microservice
    app: picvista-app

spec:
  containers:
    - name: picvista-image
      image: rachidouhammou/picvista-image
      ports:
        - containerPort: 5012
