apiVersion: v1
kind: Pod
metadata:
  name: like-pod
  labels:
    name: like-microservice
    app: picvista-app

spec:
  containers:
    - name: picvista-like
      image: rachidouhammou/picvista-like
      ports:
        - containerPort: 5014
