apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
  labels:
    name: mysql-microservice
    app: picvista-app

spec:
  containers:
    - name: picvista-db
      image: rachidouhammou/picvista-db
      ports:
        - containerPort: 3306
