apiVersion: v1
kind: Pod
metadata:
  name: user-pod
  labels:
    name: user-microservice
    app: picvista-app

spec:
  containers:
    - name: picvista-user
      image: rachidouhammou/picvista-user
      ports:
        - containerPort: 5011
