apiVersion: v1
kind: Service
metadata:
  name: user-service
  labels:
    name: user-service
    app: picvista-app

spec:
  ports:
    - port: 5011
      targetPort: 5011
  selector:
    name: user-microservice
    app: picvista-app