FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=root_password

# Create three databases during container initialization
ENV MYSQL_DATABASE_1=Comment_database
ENV MYSQL_DATABASE_2=Image_database
ENV MYSQL_DATABASE_3=Like_database
ENV MYSQL_DATABASE_4=User_database


EXPOSE 3306