name: Docker Images CI

on:
  push:
    branches: [add-github-actions]

jobs:
  deploy-clientui:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to ClientUI directory
        run: cd ./ClientUI

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./ClientUI
          file: ./ClientUI/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/picvista-clientui:v0.0.${{ github.run_number}}
            ${{ secrets.DOCKER_USER }}/picvista-clientui:latest
  
  deploy-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to Comment directory
        run: cd ./Comment

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./Comment
          file: ./Comment/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/picvista-comment:v0.0.${{ github.run_number}}
            ${{ secrets.DOCKER_USER }}/picvista-comment:latest
    
  deploy-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to Image directory
        run: cd ./image

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./image
          file: ./image/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/picvista-image:v0.0.${{ github.run_number}}
            ${{ secrets.DOCKER_USER }}/picvista-image:latest
  
  deploy-like:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to Like directory
        run: cd ./like

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./like
          file: ./like/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/picvista-like:v0.0.${{ github.run_number}}
            ${{ secrets.DOCKER_USER }}/picvista-like:latest
  
  deploy-user:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Change to User directory
        run: cd ./User

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./User
          file: ./User/Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USER }}/picvista-user:v0.0.${{ github.run_number}}
            ${{ secrets.DOCKER_USER }}/picvista-user:latest
  